# Basic
title: Hulk' Den
subtitle: in-depth thinking and keep moving.
welcome_message:
description:
creator: <a href="http://ronghaopger.github.io/about/">@RongHao</a>

url: "https://ronghaopger.github.io/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: GitHub, description: ronghaopger, url: 'https://github.com/ronghaopger'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: 做梦家荣浩
    github: ronghaopger
    mail: ronghao_1989@hotmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
